import { readFileSync } from "node:fs";
import * as T from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { MeshoptDecoder } from "three/addons/libs/meshopt_decoder.module.js";
import { BodyVolume } from "../../../src/scene/body-volume";
await MeshoptDecoder.ready;
const bytes = readFileSync("public/models/male-rigged.glb");
const g = await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), "");
g.scene.updateMatrixWorld(true);
const canon = (b: T.Object3D) => String(b.userData?.name ?? b.name).replace(/^mixamorig\d*[:_]?/i, "");
const bones = new Map<string, T.Object3D>();
g.scene.traverse((o) => { if (/^mixamorig/i.test(String(o.userData?.name ?? o.name))) bones.set(canon(o), o); });
const P = (n: string) => new T.Vector3().setFromMatrixPosition(bones.get(n)!.matrixWorld);
const body = new BodyVolume();
const I = new T.Quaternion();
body.update((s) => P(s.bone), () => I, [[P("LeftUpLeg"), P("LeftLeg")], [P("RightUpLeg"), P("RightLeg")]]);
for (const s of body.sections) console.log(s.c.toArray().map((n) => +n.toFixed(3)), s.hx, s.hz);
const n = new T.Vector3();
console.log("gap", body.gap(new T.Vector3(0, 1.163, 0.058), n), n.toArray());
console.log("gap center", body.gap(new T.Vector3(0, 1.163, -0.04), n), n.toArray());
console.log("gap front", body.gap(new T.Vector3(0, 1.163, -0.143), n), n.toArray());
console.log("gap side", body.gap(new T.Vector3(0.13, 1.163, -0.04), n), n.toArray());
