import {readFile} from "node:fs/promises";import * as T from "three";import {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";import {NodeIO} from "@gltf-transform/core";import {ALL_EXTENSIONS} from "@gltf-transform/extensions";import {MeshoptDecoder} from "meshoptimizer";
const file=process.argv[2]??"public/models/male-rigged.glb",raw=process.argv.includes("--raw"),pass:string[]=[],fail:string[]=[];const ck=(x:boolean,s:string)=>(x?pass:fail).push(s);await MeshoptDecoder.ready;const bytes=await readFile(file),io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({"meshopt.decoder":MeshoptDecoder}),doc=await io.read(file),root=doc.getRoot(),prims=root.listMeshes().flatMap(m=>m.listPrimitives()),p=prims[0];
ck(prims.length===1,"one mesh primitive");ck(bytes.length<=120*1024,"size <=120 KB");ck(raw||root.listExtensionsUsed().some(e=>e.extensionName==="EXT_meshopt_compression"),"meshopt compression present");
if(p){const pos=p.getAttribute("POSITION"),norm=p.getAttribute("NORMAL"),ji=p.getAttribute("JOINTS_0"),wt=p.getAttribute("WEIGHTS_0"),idx=p.getIndices(),skin=root.listSkins()[0];ck(!!pos&&!!norm&&!!ji&&!!wt&&!!skin,"skinned attributes and skin");ck(!p.getAttribute("TEXCOORD_0"),"no UV");ck(p.listTargets().length===0,"no morph targets");ck(!!idx&&idx.getArray() instanceof Uint16Array,"uint16 indices");ck(!!idx&&idx.getCount()%3===0&&p.getMode()===4,"triangle topology");
let wOk=!!wt;if(wt)for(let i=0;i<wt.getCount();i++){const w=[0,0,0,0];wt.getElement(i,w);let sum=0;for(const x of w){sum+=x;if(x<0)wOk=false;}if(Math.abs(sum-1)>1e-3)wOk=false;}ck(wOk,"nonzero normalized <=4 weights");
const normName=(s:string)=>s.replace(/^mixamorig[:_]?/i,"").replace(/[:_]/g,"");const sourceDoc=await io.read("tools/rig/source/human-rig.glb"),ss=sourceDoc.getRoot().listSkins()[0],srcNodes=sourceDoc.getRoot().listNodes(),outNodes=root.listNodes(),srcBy=new Map(srcNodes.map(n=>[normName(n.getName()),n])),outBy=new Map(outNodes.map(n=>[normName(n.getName()),n]));const ending=(n:string)=>/(?:Hand(?:Thumb|Index|Middle|Ring|Pinky)?4|Toe_End|HeadTop_End)$/.test(n);const required=ss.listJoints().map(n=>({node:n,name:normName(n.getName())})).filter(x=>!ending(x.node.getName())).map(x=>x.name);const outputSkin=root.listSkins()[0];const outJointNames=outputSkin.listJoints().map(n=>normName(n.getName()));ck(required.every(n=>outJointNames.includes(n)),"Mixamo joints preserved except optional end markers");ck(outJointNames.every(n=>srcBy.has(n)),"no non-source bones");
let hier=true;for(const name of required){const a=srcBy.get(name),b=outBy.get(name);if(!a||!b){hier=false;continue;}let ap=a.getParentNode(),bp=b.getParentNode();while(ap&&!ss.listJoints().includes(ap))ap=ap.getParentNode();while(bp&&!outputSkin.listJoints().includes(bp))bp=bp.getParentNode();if(normName(ap?.getName()??"")!==normName(bp?.getName()??""))hier=false;}ck(hier,"joint hierarchy matches source");
const load=async(path:string)=>{const b=await readFile(path),g=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder as any).parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),"");g.scene.updateMatrixWorld(true);let sm:T.SkinnedMesh|undefined;g.scene.traverse(o=>{if((o as T.SkinnedMesh).isSkinnedMesh)sm=o as T.SkinnedMesh;});if(!sm)throw Error(`No skinned mesh in ${path}`);sm.skeleton.update();return {g,sm};};
const source=await load("tools/rig/source/human-rig.glb"),output=await load(file);const bnd=(sm:T.SkinnedMesh)=>{const b=new T.Box3();for(let i=0;i<sm.geometry.getAttribute("position").count;i++)b.expandByPoint(sm.getVertexPosition(i,new T.Vector3()).applyMatrix4(sm.matrixWorld));return b;};const oldBox=bnd(source.sm),rot=new T.Matrix4().makeRotationY(-Math.PI/2),rs=rot.clone().multiply(new T.Matrix4().makeScale(1.8,1.8,1.8));const moved=new T.Box3();for(let i=0;i<source.sm.geometry.getAttribute("position").count;i++)moved.expandByPoint(source.sm.getVertexPosition(i,new T.Vector3()).applyMatrix4(source.sm.matrixWorld).applyMatrix4(rs));const trans=new T.Matrix4().makeTranslation(-(moved.min.x+moved.max.x)/2,-moved.min.y,0),N=trans.multiply(rs);const box=bnd(output.sm);ck(Math.abs(box.min.y)<1e-3&&Math.abs(box.max.y-1.8)<1e-3&&Math.abs(box.min.x+box.max.x)<1e-3,"skinned bind-pose app-space bounds");
// Every output vertex is checked against its nearest source bind-pose vertex after N (welding/reorder remove index correspondence).
const oldPoints:T.Vector3[]=[];for(let i=0;i<source.sm.geometry.getAttribute("position").count;i++)oldPoints.push(source.sm.getVertexPosition(i,new T.Vector3()).applyMatrix4(source.sm.matrixWorld).applyMatrix4(N));let sampleOk=true;const count=output.sm.geometry.getAttribute("position").count;for(let k=0;k<200;k++){const i=Math.floor(k*(count-1)/199),q=output.sm.getVertexPosition(i,new T.Vector3()).applyMatrix4(output.sm.matrixWorld);let nearest=Infinity;for(const op of oldPoints)nearest=Math.min(nearest,q.distanceTo(op));if(nearest>0.001)sampleOk=false;}ck(sampleOk,"200 skinned vertices match normalized source within 1 mm");
const sbones=new Map(source.sm.skeleton.bones.map(b=>[normName(b.name),b]));let restOk=true;for(const bone of output.sm.skeleton.bones){const src=sbones.get(normName(bone.name));if(!src)continue;const expected=src.getWorldPosition(new T.Vector3()).applyMatrix4(N),actual=bone.getWorldPosition(new T.Vector3());if(expected.distanceTo(actual)>0.001)restOk=false;}ck(restOk,"joint world rest positions transformed from source within 1 mm");
const boneMap=new Map(output.sm.skeleton.bones.map(b=>[normName(b.name),b]));const hand=boneMap.get("LeftHand"),toe=boneMap.get("LeftToeBase"),foot=boneMap.get("LeftFoot");ck(!!hand&&hand.getWorldPosition(new T.Vector3()).x<0&&!!toe&&!!foot&&toe.getWorldPosition(new T.Vector3()).z<foot.getWorldPosition(new T.Vector3()).z,"left hand -X; toes -Z");void oldBox;
}
for(const x of pass)console.log(`PASS ${x}`);for(const x of fail)console.error(`FAIL ${x}`);console.log(`${fail.length?"FAIL":"PASS"} ${file} ${bytes.length} bytes`);if(fail.length)process.exitCode=1;
